## ======================================================================================
## Hexo Theme Keep
## æ–‡æ¡£: https://keep-docs.xpoet.cn
## ä»“åº“: https://github.com/XPoet/hexo-theme-keep
## ======================================================================================

# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/base_info.html
# ---------------------------------------------------------------------------------------
base_info:
  # ä¸»é¢˜åŸè‰²
  primary_color: "#39c5bb"

  # åšå®¢ç½‘ç«™æ ‡é¢˜
  title: Railgun's Blog

  # åšå®¢ç½‘ç«™ä½œè€…åç§°
  author: Railgun

  # ä½œè€…å¤´åƒï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æœ¬åœ°å›¾ç‰‡è·¯å¾„æˆ–å›¾ç‰‡é“¾æ¥
  avatar: https://fastly.jsdelivr.net/gh/MikuHello/Assets/B_compress_1m.png

  # ç½‘ç«™ LOGOï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æœ¬åœ°å›¾ç‰‡è·¯å¾„æˆ–å›¾ç‰‡é“¾æ¥
  logo: https://fastly.jsdelivr.net/gh/MikuHello/Assets/Logo_Full.png

  # ç½‘ç«™ faviconï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æœ¬åœ°å›¾ç‰‡è·¯å¾„æˆ–å›¾ç‰‡é“¾æ¥
  favicon: https://fastly.jsdelivr.net/gh/MikuHello/Assets/Logo_Full.png
  
  # å¯é€‰å€¼: light | dark (äº®è‰² | æš—è‰²)
  mode: dark


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/menu.html
# ---------------------------------------------------------------------------------------
# å¦‚æœæ‚¨æƒ³å¯ç”¨æ–°çš„å¯¼èˆªèœå•ï¼Œæ‚¨éœ€è¦åˆ›å»ºç›¸åº”çš„é¡µé¢
# ä¾‹å¦‚ï¼šè¦å¯ç”¨ categories (åˆ†ç±»)ï¼Œæ‚¨éœ€è¦æ‰§è¡Œ `hexo new page categories`
# ä½¿ç”¨ `||` ä¸ºå¯¼èˆªèœå•è®¾ç½®å›¾æ ‡ï¼Œä¾‹å¦‚ `home: / || fa-solid fa-home`
menu:
  home: /                      || fa-solid fa-home
  archives: /archives          || fa-solid fa-box-archive
  tags: /tags                  || fa-solid fa-tags
  links: /links                || fa-solid fa-link
  about: /about                || fa-solid fa-user-graduate


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/first_screen.html
# ---------------------------------------------------------------------------------------
first_screen:
  enable: true  # å¯é€‰å€¼: true | false (å¼€å¯ | å…³é—­)

  # äº®è‰²æ¨¡å¼ä¸‹çš„é¦–å±èƒŒæ™¯å›¾ç‰‡ï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æœ¬åœ°å›¾ç‰‡è·¯å¾„æˆ–å›¾ç‰‡é“¾æ¥
  background_img: /images/bg.svg

  # æš—è‰²æ¨¡å¼ä¸‹çš„é¦–å±èƒŒæ™¯å›¾ç‰‡ï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æœ¬åœ°å›¾ç‰‡è·¯å¾„æˆ–å›¾ç‰‡é“¾æ¥
  background_img_dark: /images/bg.svg

  # é¦–å±æè¿°
  # æ‚¨å¯ä»¥ä½¿ç”¨ "||" æ¥æ¢è¡Œï¼Œæœ€å¤šä¸¤è¡Œ
  description: Strive to become a network layman. o(*////â–½////*)q

  # å¦‚æœå¯ç”¨ hitokoto (ä¸€è¨€)ï¼Œæ¯æ¬¡è¿›å…¥ç½‘ç«™æ—¶é¦–å±æè¿°éƒ½ä¼šä¸åŒ
  hitokoto: false      # å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/social_contact.html
# ---------------------------------------------------------------------------------------
social_contact:
  enable: true      # å¯é€‰å€¼: true | false
  links:
    # åœ¨è¿™é‡Œå¡«å†™æ‚¨çš„ç¤¾äº¤å¹³å°é“¾æ¥ï¼Œä¾‹å¦‚ `github: https://github.com/XPoet`
    # å¦‚æœæ‚¨å¸Œæœ›ç‚¹å‡»æ‰“å¼€å›¾ç‰‡ï¼Œæ‚¨éœ€è¦æ·»åŠ å‰ç¼€ `img | `
    # åŒæ—¶å°†æ‚¨çš„é“¾æ¥æ›´æ”¹ä¸ºå›¾ç‰‡é“¾æ¥ã€‚
    # ä¾‹å¦‚ `weixin: img | ./images/qrcode.png`
    github: https://github.com/MikuHello          # GitHub
	bilibili: https://space.bilibili.com/2035035843
    #weixin:          # å¾®ä¿¡
    #qq:              # QQ
    #weibo:           # å¾®åš
    #zhihu:           # çŸ¥ä¹
    #twitter:         # Twitter
    #x:               # X
    #facebook:        # Facebook
    #email:           # ç”µå­é‚®ä»¶


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/scroll.html
# ---------------------------------------------------------------------------------------
scroll:
  # é¡µé¢æ»šåŠ¨æ—¶åœ¨é¡¶éƒ¨æ˜¾ç¤ºè¿›åº¦æ¡
  progress_bar: true  # å¯é€‰å€¼: true | false

  # é¡µé¢æ»šåŠ¨æ—¶æ˜¾ç¤ºç™¾åˆ†æ¯”
  percent: true       # å¯é€‰å€¼: true | false

  # é¡µé¢æ»šåŠ¨æ—¶éšè—é¡¶éƒ¨å¯¼èˆªæ 
  hide_header: true    # å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/home.html
# ---------------------------------------------------------------------------------------
home:
  # ä¸»é¡µä¸Šçš„ç½‘ç«™å…¬å‘Š
  announcement: æ­å»ºä¸­

  # åœ¨ä¸»é¡µæ–‡ç« å—ä¸­æ˜¾ç¤ºåˆ†ç±»
  category: true           # å¯é€‰å€¼: true | false

  # åœ¨ä¸»é¡µæ–‡ç« å—ä¸­æ˜¾ç¤ºæ ‡ç­¾
  tag: true                # å¯é€‰å€¼: true | false

  # è®¾ç½®ä¸»é¡µæ–‡ç« å—çš„æ—¥æœŸæ—¶é—´ç±»å‹
  post_datetime: updated    # å¯é€‰å€¼: updated (æ›´æ–°æ—¶é—´) | created (åˆ›å»ºæ—¶é—´)


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/post.html
# ---------------------------------------------------------------------------------------
post:
  # æ–‡ç« ä¸­çš„ä½œè€…å¾½ç« 
  author_badge:
    enable: true         # å¯é€‰å€¼: true | false

    # å¦‚æœä¸º trueï¼Œæ˜¾ç¤º Lv1, Lv2, Lv3 ...
    # å¦‚æœä¸º falseï¼Œæ˜¾ç¤ºè‡ªå®šä¹‰å¾½ç« 
    level_badge: false    # å¯é€‰å€¼: true | false

    # è‡ªå®šä¹‰å¾½ç« æ•°ç»„ï¼Œæ‚¨å¯ä»¥å¡«å†™ä¸€é¡¹æˆ–å¤šé¡¹
    custom_badge: ğ“¡ğ“ªğ“²ğ“µğ“°ğ“¾ğ“·

  # æ–‡ç« å­—æ•°ç»Ÿè®¡
  # ä¾èµ– Hexo æ’ä»¶: hexo-wordcount (`npm install hexo-wordcount`)
  # å‚è§: https://github.com/willin/hexo-wordcount
  word_count:
    wordcount: true     # å­—æ•°ç»Ÿè®¡ (å•ç¯‡æ–‡ç« )ã€‚å¯é€‰å€¼: true | false
    min2read: true      # é˜…è¯»æ—¶é•¿ (å•ç¯‡æ–‡ç« )ã€‚å¯é€‰å€¼: true | false

  # æ–‡ç« æ—¥æœŸæ—¶é—´
  datetime_format: "YYYY-MM-DD HH:mm:ss"  # æ—¥æœŸæ—¶é—´æ ¼å¼ã€‚ä¾‹å¦‚ "YYYY-MM-DD HH:mm:ss"

  # æ–‡ç« ç‰ˆæƒä¿¡æ¯
  copyright_info: true  # å¯é€‰å€¼: true | false

  # æ–‡ç« åˆ†äº«
  share: true           # å¯é€‰å€¼: true | false

  # æ‰“èµä½œè€…
  reward:
    enable: true        # å¯é€‰å€¼: true | false
    img_link: https://fastly.jsdelivr.net/gh/MikuHello/Assets/reward.jpg            # ä»˜æ¬¾äºŒç»´ç çš„å›¾ç‰‡é“¾æ¥
    text:                # è‡ªå®šä¹‰æ‰“èµæ–‡æœ¬ï¼Œå¯ä¸ºç©º
    icon:                # è‡ªå®šä¹‰æ‰“èµå›¾æ ‡ï¼Œå¯ä¸ºç©º


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/code_block.html
# ---------------------------------------------------------------------------------------
code_block:
  # å·¥å…·æ åŒ…æ‹¬ï¼š"å¤åˆ¶ä»£ç ", "æŠ˜å ä»£ç å—" å’Œ "ä»£ç è¯­è¨€"
  tools:
    enable: true            # å¯é€‰å€¼: true | false
    style: default           # å¯é€‰å€¼: default (é»˜è®¤) | mac (mac é£æ ¼)
  highlight_theme: default   # é«˜äº®ä¸»é¢˜ã€‚å¯é€‰å€¼: default | obsidian


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/toc.html
# ---------------------------------------------------------------------------------------
toc:
  enable: true      # å¯é€‰å€¼: true | false

  # è‡ªåŠ¨ä¸ºç›®å½•æ·»åŠ åˆ—è¡¨ç¼–å·
  number: false      # å¯é€‰å€¼: true | false

  # å¦‚æœä¸º trueï¼Œæ–‡ç« ä¸­çš„æ‰€æœ‰çº§åˆ«çš„ç›®å½•éƒ½å°†æ˜¾ç¤ºï¼Œè€Œä¸ä»…ä»…æ˜¯æ¿€æ´»çš„éƒ¨åˆ†
  expand_all: true  # å¯é€‰å€¼: true | false

  # å¦‚æœä¸º trueï¼Œæ¯æ¬¡è¿›å…¥æ–‡ç« é¡µé¢æ—¶è‡ªåŠ¨æ‰“å¼€ç›®å½•
  init_open: true    # å¯é€‰å€¼: true | false

  # æ–‡ç« é¡µé¢ä¸Šçš„ç›®å½•å¸ƒå±€
  layout: right      # å¯é€‰å€¼: left (å·¦ä¾§) | right (å³ä¾§)


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/website_count.html
# ---------------------------------------------------------------------------------------
website_count:
  # ä¸è’œå­
  # å‚è§: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true     # å¯é€‰å€¼: true | false
    site_uv: true    # ç½‘ç«™è®¿å®¢æ•°ã€‚å¯é€‰å€¼: true | false
    site_pv: true    # ç½‘ç«™è®¿é—®é‡ã€‚å¯é€‰å€¼: true | false
    page_pv: true    # é¡µé¢é˜…è¯»é‡ã€‚å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/local_search.html
# ä¾èµ– Hexo æ’ä»¶: hexo-generator-searchdb (`npm install hexo-generator-searchdb`)
# å‚è§: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true   # å¯é€‰å€¼: true | false
  preload: true  # é¡µé¢åŠ è½½æ—¶é¢„åŠ è½½æœç´¢æ•°æ®ã€‚å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/comment.html
# ---------------------------------------------------------------------------------------
comment:
  enable: true   # å¯é€‰å€¼: true | false
  use: giscus     # å¯é€‰å€¼: valine | gitalk | twikoo | waline | giscus | artalk | disqus

  # Valine
  # å‚è§: https://github.com/xCss/Valine
  #      https://valine.js.org
  valine:
    appid:           # æ‚¨çš„ leancloud åº”ç”¨ appid
    appkey:          # æ‚¨çš„ leancloud åº”ç”¨ appkey
    server_urls:     # æ‚¨çš„æœåŠ¡å™¨ URL
    placeholder:     # è¾“å…¥æ¡†å ä½ç¬¦

  # Gitalk
  # å‚è§: https://github.com/gitalk/gitalk
  #      https://gitalk.github.io
  gitalk:
    github_id:        # GitHub ä»“åº“æ‰€æœ‰è€…
    github_admins:    # GitHub ç®¡ç†å‘˜ (æ•°ç»„ç±»å‹)ï¼Œå¯é€‰
    repository:       # å­˜å‚¨ issues çš„ä»“åº“åç§°
    client_id:        # GitHub Application Client ID
    client_secret:    # GitHub Application Client Secret
    proxy:            # ç”¨äº CORS çš„ GitHub oauth è¯·æ±‚åå‘ä»£ç†

  # Twikoo
  # å‚è§: https://github.com/imaegoo/twikoo
  #      https://twikoo.js.org
  twikoo:
    env_id:          # ç¯å¢ƒ ID
    region:          # ç¯å¢ƒåŒºåŸŸï¼Œå¯ä¸ºç©º
    version: 1.6.39  # Twikoo ç‰ˆæœ¬ï¼Œé»˜è®¤ä½¿ç”¨ v1.6.39

  # Waline
  # å‚è§: https://github.com/walinejs/waline
  #      https://waline.js.org/guide/get-started.html
  waline:
    server_url:         # æœåŠ¡å™¨ URL
    reaction: false     # æ–‡ç« ååº”ï¼Œå¯é€‰å€¼: true | false
    version: 3.3.2      # Waline ç‰ˆæœ¬ï¼Œé»˜è®¤ä½¿ç”¨ v3.3.2

  # Giscus
  # å‚è§: https://github.com/giscus/giscus
  #      https://giscus.app
  # è¯·åœ¨ https://giscus.app ç”Ÿæˆæ‚¨çš„é…ç½®é¡¹
  giscus:
    repo: MikuHello/Hexo-Site
    repo_id: R_kgDOQTXpgA
    category: Announcements    # æ¨èä½¿ç”¨ Announcements
    category_id: DIC_kwDOQTXpgM4Cxr2A
    reactions_enabled: true   # å¯é€‰å€¼: true | false
    mapping: pathname
    emit_metadata: false
    input_position: bottom
    theme: preferred_color_scheme
    strict: false
    loading: lazy

  # Artalk
  # å‚è§: https://github.com/ArtalkJS/Artalk
  #      https://artalk.js.org
  artalk:
    server:                    # æœåŠ¡å™¨ URL

  # Disqus
  # å‚è§: https://disqus.com/
  disqus:
    shortname:                 # Disqus Shortname


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/rss.html
# ä¾èµ– Hexo æ’ä»¶: hexo-generator-feed (`npm install hexo-generator-feed`)
# å‚è§: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: true  # å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/lazyload.html
# ---------------------------------------------------------------------------------------
lazyload:
  enable: true  # å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/cdn.html
# ---------------------------------------------------------------------------------------
cdn:
  enable: true       # å¯é€‰å€¼: true | false
  provider: cdnjs     # å¯é€‰å€¼: cdnjs | jsdelivr | unpkg


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/pjax.html
# ---------------------------------------------------------------------------------------
pjax:
  enable: true  # å¯é€‰å€¼: true | false


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/footer.html
# ---------------------------------------------------------------------------------------
footer:
  since: 2025            # æ‚¨ç½‘ç«™çš„èµ·å§‹å¹´ä»½ï¼Œå¯ä¸ºç©º
  word_count: true      # ç½‘ç«™æ€»å­—æ•°ç»Ÿè®¡ã€‚å¯é€‰å€¼: true | false

  site_deploy:
    enable: true        # å¯é€‰å€¼: true | false
    provider: cloudflare     # éƒ¨ç½²æä¾›å•†ã€‚å¯é€‰å€¼: github | vercel | netlify | cloudflare | gitee | aliyun | tencent_cloud | upyun
    url: https://hexo-site.pages.dev                 # æ‚¨çš„éƒ¨ç½²æä¾›å•†ç½‘å€ï¼Œå¯ä¸ºç©º

  record:
    enable: false        # å¤‡æ¡ˆä¿¡æ¯ã€‚å¯é€‰å€¼: true | false
    list:
      - code:            # æ‚¨ç½‘ç«™çš„å¤‡æ¡ˆå·
        link:            # æ‚¨ç½‘ç«™çš„å¤‡æ¡ˆé“¾æ¥ï¼Œå¯ä¸ºç©º
      # ä¾‹å¦‚
      # - code: ICP å¤‡ 001 å·
      # - link: https://beian.miit.gov.cn


# ---------------------------------------------------------------------------------------
# æ–‡æ¡£: https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html
# ---------------------------------------------------------------------------------------
inject:
  enable: false  # è‡ªå®šä¹‰æ³¨å…¥ã€‚å¯é€‰å€¼: true | false
  css:
    -
    # ä¾‹å¦‚
    # - /css/custom-1.css
    # - /css/custom-2.css
    # - ...
  js:
    -
    # ä¾‹å¦‚
    # - /js/custom-1.js
    # - /js/custom-2.js
    # - ...